import type { PublicPortfolioView } from '../../../../types/dto';

interface AtsTemplateProps {
  portfolio: PublicPortfolioView;
}

// Helper to safely extract string properties from section
function getSectionProperty(section: Record<string, unknown>, key: string): string | null {
  const value = section[key];
  return typeof value === 'string' ? value : null;
}

/**
 * ATS portfolio template - text-only (no images), optimized for Applicant Tracking Systems
 * Includes banner warning, auto-includes social links and email
 */
export function AtsTemplate({ portfolio }: AtsTemplateProps) {
  const { title, description, sections } = portfolio;

  return (
    <div className="min-h-screen bg-white">
      {/* ATS Warning Banner */}
      <div className="bg-yellow-50 border-b border-yellow-200 p-4">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-2 text-yellow-800">
            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
            </svg>
            <span className="font-medium">ATS Template: Text-only format optimized for Applicant Tracking Systems</span>
          </div>
        </div>
      </div>

      {/* Header */}
      <header className="border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-6 py-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-4">
            {title}
          </h1>
          {description && (
            <p className="text-lg text-gray-700 mb-6">
              {description}
            </p>
          )}
          
          {/* Contact Information - Always visible in ATS template */}
          <div className="space-y-2 text-gray-700">
            <p className="font-medium">Contact Information:</p>
            <div className="space-y-1 text-sm">
              <p>Email: [Contact email from profile]</p>
              <p>GitHub: [GitHub profile]</p>
              <p>Portfolio: [This portfolio URL]</p>
            </div>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-8">
        {sections && sections.length > 0 ? (
          <div className="space-y-8">
            {sections.map((section, index) => {
              const sectionTitle = getSectionProperty(section, 'title');
              const sectionContent = getSectionProperty(section, 'content');
              // Note: Images are intentionally excluded in ATS template

              return (
                <section key={index} className="border-b border-gray-100 pb-6 last:border-b-0">
                  {/* Section Title */}
                  {sectionTitle && (
                    <h2 className="text-xl font-semibold text-gray-900 mb-3 uppercase tracking-wide">
                      {sectionTitle}
                    </h2>
                  )}

                  {/* Section Content - Text only */}
                  {sectionContent && (
                    <div className="text-gray-700 leading-relaxed">
                      <pre className="whitespace-pre-wrap font-sans text-sm">
                        {sectionContent}
                      </pre>
                    </div>
                  )}
                </section>
              );
            })}
          </div>
        ) : (
          <div className="text-center py-12">
            <p className="text-gray-600">No sections available</p>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-200 mt-12">
        <div className="max-w-4xl mx-auto px-6 py-6">
          <div className="text-center text-sm text-gray-500">
            <p>Generated by Porflyo - ATS Optimized Format</p>
            <p className="mt-1">This resume is designed for maximum compatibility with Applicant Tracking Systems</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
