AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# SAM Configuration for Micronaut Lambda with AOT Optimizations
# Uses the optimized JAR: build/libs/core-0.1-all-optimized.jar
# This JAR includes all dependencies + Micronaut AOT optimizations for faster cold starts

Globals:
  Function:
    Timeout: 50
    Environment:
      Variables:
        # Optimize JVM for Lambda cold start
        JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -Xms128m -Xmx256m -XX:+OptimizeStringConcat -XX:+UseStringDeduplication -XX:+UseCompressedOops"
        # Micronaut Lambda optimizations  
        MICRONAUT_ENVIRONMENTS: "lambda"
        MICRONAUT_CONTEXT_EAGER_INIT: "true"
        MICRONAUT_SERVER_NETTY_ENABLED: "false"

Resources:
  PorflyoApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.porflyo.infrastructure.adapters.input.lambda.entrypoint.LambdaEntryPointHandler::execute
      Runtime: java21
      MemorySize: 256
      Environment:
        Variables:
          OAUTH_GITHUB_CLIENT_ID: !Ref OAUTH_CLIENT_ID
          OAUTH_GITHUB_CLIENT_SECRET: !Ref OAUTH_CLIENT_SECRET
          OAUTH_GITHUB_REDIRECT_URI: !Ref OAUTH_REDIRECT_URI
          OAUTH_GITHUB_SCOPE: !Ref OAUTH_SCOPE
          OAUTH_GITHUB_USER_AGENT: !Ref OAUTH_USER_AGENT
          JWT_SECRET: !Ref JWT_SECRET
          JWT_EXPIRATION: !Ref JWT_EXPIRATION
          FRONTEND_URL: !Ref FRONTEND_URL
      Events:
        # Handle all HTTP requests
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        # Handle root path
        HttpApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

Outputs:
  PorflyoApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub BackendUrl
  OAuthLoginUrl:
    Description: "GitHub OAuth login URL"
    Value: !Sub  OauthLoginUrl